import type { Express } from "express";
import { createServer, type Server } from "http";
import { storage } from "./storage";
import OpenAI from "openai";

// Read API key from environment variable
// Set OPENAI_API_KEY in .env locally or in Vercel dashboard for production
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || "";

const openai = new OpenAI({ apiKey: OPENAI_API_KEY });

const CHAT_SYSTEM_PROMPT = `You are MemoryForge, a friendly AI assistant that builds a personal AI context/memory file for the user. You guide them through 11 structured sections, asking 2-3 questions at a time per section, then moving on once you have enough info.

SECTIONS (cover in order):
1. Identity & Background - name, description, location/timezone, career story, long-term goals, values
2. Business Overview - business name/description, products/services, target customer, problem solved, business model, markets, maturity stage
3. Brand, Positioning & Voice - positioning vs competitors, brand adjectives, competitors/differentiators, formality scale 1-10, phrases to avoid, tagline/elevator pitch
4. Operations, Tools & Workflows - daily tools/platforms, lead/sales channels, top 3 workflows for AI help, key KPIs, team size/roles, SOPs
5. Customers, Problems & Objections - ideal customer avatar, top 3 customer pains, top 3 customer wins, common objections, proof/evidence used, customer segments to prioritize
6. Current Priorities & Constraints - top 3 priorities for next 90 days, biggest bottlenecks, current projects in progress, tasks for AI vs human, non-negotiable constraints
7. Personal Preferences for AI Help - ideal AI job description, challenge vs support preference, directness scale 1-10, answer detail preference, response formats, handling uncertainty, default tools/stack, language/spelling/units
8. Knowledge Boundaries & Sources - authoritative internal sources, topics to defer to user judgment, external sources/frameworks followed, handling conflicting info
9. Security, Privacy & Boundaries - off-limits information, tasks AI should never perform, anonymize client details preference
10. House Rules & Meta-Preferences - what AI should always do, what AI should never do, how to handle unknowns, examples of perfect responses
11. Technical & Coding Profile (Optional) - programming languages/frameworks, code style conventions, environment assumptions, how AI should help with code

RULES:
- Ask 2-3 questions per section max, then say "Got it, moving on to Section X: [name]"
- Keep responses concise and warm — no more than 4-5 lines per response
- If user says "skip" or "not applicable", accept it and move on immediately
- Track which section you are on and never go back unless user asks
- After completing section 11 (or if user skips it), respond with exactly: GENERATE_MEMORY_FILE followed by a JSON block summarizing all collected data by section
- Never keep drilling deeper into one topic — get the key info and move forward
- Do NOT ask more than 3 questions before moving to next section

START: Introduce yourself in 2 sentences and begin Section 1 with the first 2-3 questions.`;

const MEMORY_SYSTEM_PROMPT = `Based on this conversation, generate a beautifully formatted personal AI memory file in Markdown. Use this exact structure:

# AI Memory File — [Name]
*Generated by MemoryForge on [today's date]*

## Quick Summary
[2-3 sentence overview of who they are, what they do, and what they want from AI]

## 1. Identity & Background
[bullet points for each piece of info collected]

## 2. Business Overview
[bullet points]

## 3. Brand, Positioning & Voice
[bullet points]

## 4. Operations, Tools & Workflows
[bullet points]

## 5. Customers, Problems & Objections
[bullet points]

## 6. Current Priorities & Constraints
[bullet points]

## 7. Personal AI Preferences
[bullet points]

## 8. Knowledge Boundaries & Sources
[bullet points]

## 9. Security, Privacy & Boundaries
[bullet points]

## 10. House Rules for AI
Always:
- [list]
Never:
- [list]

## 11. Technical & Coding Profile
[bullet points, or "Not applicable" if skipped]

---
*This file was generated by MemoryForge. Paste it into any AI system to give it instant context about you.*`;

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<Server> {
  // POST /api/chat — conversational endpoint
  app.post("/api/chat", async (req, res) => {
    try {
      const { messages, collectedData } = req.body;

      if (!messages || !Array.isArray(messages)) {
        return res.status(400).json({ message: "messages array is required" });
      }

      // Build the messages array for OpenAI
      const openaiMessages: OpenAI.Chat.Completions.ChatCompletionMessageParam[] =
        [
          { role: "system" as const, content: CHAT_SYSTEM_PROMPT },
          ...messages.map(
            (m: { role: string; content: string }) =>
              ({
                role: m.role as "user" | "assistant",
                content: m.content,
              }) as OpenAI.Chat.Completions.ChatCompletionMessageParam
          ),
        ];

      const completion = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: openaiMessages,
        temperature: 0.7,
        max_tokens: 1024,
      });

      const responseContent =
        completion.choices[0]?.message?.content || "I'm sorry, I couldn't generate a response.";

      const isComplete = responseContent.includes("GENERATE_MEMORY_FILE");

      return res.json({
        message: responseContent,
        isComplete,
      });
    } catch (error: any) {
      console.error("OpenAI API error:", error?.message || error);
      return res
        .status(500)
        .json({ message: "Failed to get AI response. Please try again." });
    }
  });

  // POST /api/generate-memory — generate the memory file
  app.post("/api/generate-memory", async (req, res) => {
    try {
      const { messages } = req.body;

      if (!messages || !Array.isArray(messages)) {
        return res.status(400).json({ memoryFile: "messages array is required" });
      }

      // Build conversation context for the memory generation
      const openaiMessages: OpenAI.Chat.Completions.ChatCompletionMessageParam[] =
        [
          { role: "system" as const, content: MEMORY_SYSTEM_PROMPT },
          ...messages.map(
            (m: { role: string; content: string }) =>
              ({
                role: m.role as "user" | "assistant",
                content: m.content,
              }) as OpenAI.Chat.Completions.ChatCompletionMessageParam
          ),
          {
            role: "user" as const,
            content:
              "Please generate my personal AI memory file now based on our conversation above.",
          },
        ];

      const completion = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: openaiMessages,
        temperature: 0.5,
        max_tokens: 2048,
      });

      const memoryFile =
        completion.choices[0]?.message?.content || "Failed to generate memory file.";

      return res.json({ memoryFile });
    } catch (error: any) {
      console.error("OpenAI API error:", error?.message || error);
      return res
        .status(500)
        .json({ memoryFile: "Failed to generate memory file. Please try again." });
    }
  });

  return httpServer;
}
